baseURL = "https://aannttoo.github.io"
languageCode = "en-us"
title = "@anthony's Home page"
theme = "cpshallo"
[Author]
    name = "Anthony Prakash"
[params]
    [params.colors]
        background = "#9651b5"
        foreground = "#edf7ff"
        hover = "#ffba82"
    [[params.links]]
        icon = "wordpress"
        title = "Blog"
        url = "https://blog.thestateofme.com"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/cpswan"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/cpswan"
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/chrisswan/"
    [[params.links]]
        icon = "slideshare"
        title = "Slideshare"
        url = "https://www.slideshare.net/cpswan"
    [[params.links]]
        icon = "delicious"
        title = "Pinboard"
        url = "https://pinboard.in/u:cpswan"
    [[params.links]]
        icon = "docker"
        title = "Docker Hub"
        url = "https://hub.docker.com/u/cpswan"
    [[params.links]]
        icon = "untappd"
        title = "Untappd"
        url = "https://untappd.com/user/cpswan"
